import PDFDocument from 'pdfkit';

export function generateContract({
  projectType,
  pricingModel,
  paymentSchedule,
  revisionLimit,
  clientName,
  projectDescription
}) {
  const today = new Date().toLocaleDateString('en-US', { 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric' 
  });

  let contract = `# SERVICE AGREEMENT

**Date:** ${today}  
**Client:** ${clientName}  
**Project Type:** ${projectType}

---

## 1. SCOPE OF WORK

${projectDescription}

This agreement covers the services described above, delivered according to the specifications and timeline agreed upon.

---

## 2. PAYMENT TERMS

`;

  // Pricing model section
  if (pricingModel === 'fixed') {
    contract += `**Fixed Price:** The total project fee is [AMOUNT] USD, payable according to the schedule below.\n\n`;
  } else if (pricingModel === 'hourly') {
    contract += `**Hourly Rate:** Services will be billed at [RATE] USD per hour, with invoices submitted [FREQUENCY].\n\n`;
  }

  // Payment schedule
  if (paymentSchedule === 'upfront') {
    contract += `**Payment Schedule:** 100% payment due upfront before work begins.\n\n`;
  } else if (paymentSchedule === 'milestones') {
    contract += `**Payment Schedule:** Payment will be made in milestones:
- 50% upfront
- 50% upon completion\n\n`;
  } else if (paymentSchedule === 'on-delivery') {
    contract += `**Payment Schedule:** Payment due upon delivery of completed work.\n\n`;
  }

  contract += `**Late Payment:** Invoices not paid within 7 days of due date will incur a 5% late fee per week.\n\n`;

  contract += `---

## 3. REVISIONS

The project includes **${revisionLimit} round(s) of revisions** included in the base price. Additional revisions will be billed at [RATE] per hour or [AMOUNT] per revision.

---

## 4. TIMELINE

- **Start Date:** [START DATE]
- **Expected Completion:** [COMPLETION DATE]
- **Deliverables:** [LIST DELIVERABLES]

---

## 5. INTELLECTUAL PROPERTY

Upon full payment, all rights to the work will transfer to the Client. Until payment is complete, all work remains the property of the Freelancer.

---

## 6. TERMINATION

Either party may terminate this agreement with 7 days written notice. Work completed up to the termination date will be invoiced and paid according to the payment terms above.

---

## 7. DISCLAIMER

This contract is a template and should be reviewed by a legal professional before use. The parties agree that this is a general service agreement and may need customization based on jurisdiction and specific circumstances.

---

## SIGNATURES

**Freelancer:** _________________  
**Date:** ${today}

**Client:** _________________  
**Date:** _______________

---

*Generated by Freelance Shield - A risk-aware toolkit for freelancers*`;

  return contract;
}

export function createContractPdfBuffer(contractText) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const buffers = [];

    doc.on('data', (chunk) => buffers.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(buffers)));
    doc.on('error', reject);

    doc.font('Times-Roman').fontSize(11).text(contractText, {
      align: 'left',
      lineGap: 4,
      paragraphGap: 6
    });

    doc.end();
  });
}

